### ISSUE TITLE
responsiveness for each screen

### ISSUE THREAD

**Issue by fiizzy** [fiizzy/calentre#41]
Create a responsive view for each screen of the design. **Please create a PR for each responsive screen**.

Support
- [ ] Android
- [ ] iOS
- [ ] Web (mobile)

**Comment by 21kkfy** [comment]
Working on the issue now. Here are the initial situations:
![image](https://github.com/fiizzy/calentre/assets/98432874/28801b49-a9aa-400b-a7c1-da6c1f86803c)
![image](https://github.com/fiizzy/calentre/assets/98432874/0b65f6d2-62a6-450c-9de1-8a9c601be023)
![image](https://github.com/fiizzy/calentre/assets/98432874/aec96c51-eed6-477d-b715-9af2a15a7eb5)

**Comment by fiizzy** [comment]
Closing down this issue it has started being worked on in smaller issues.
